version: 1
name: IncubatorConfigs
alias: IFConf
script: IF_Core_Debug_Global
help: Console functions to debug and inspect configuration data
subs:
- name: ConfigsReload
  alias: r
  func: configsReload 
  help: Reloads all configuration files.

- name: ConfigsUpdateCaches
  alias: uc
  func: configsUpdateCaches
  help: Refreshes all internal caches from config data.



- name: ConfigsContainersShow
  alias: csh
  func: configsContainersShow
  help: Displays properties of the specified container from configuration.
  args:
  - name: id
    type: string
    required: true
    help: The container ID to inspect.

- name: ConfigsContainersShowAll
  alias: csha
  func: configsContainersShowAll
  help: Displays all available container IDs from configuration.



- name: ConfigsLiquidsShow
  alias: lsh
  func: configsLiquidsShow
  help: Displays properties and morph effects of the specified liquid.
  args:
  - name: id
    type: string
    required: true
    help: The liquid ID to inspect.

- name: ConfigsLiquidsShowAll
  alias: lsha
  func: configsLiquidsShowAll
  help: Displays all available liquid IDs from configuration.



- name: ConfigsObjectsShow
  alias: osh
  func: configsObjectsShow
  help: Displays properties and morph effects of the specified object.
  args:
  - name: id
    type: string
    required: true
    help: The object ID to inspect.

- name: ConfigsObjectsShowAll
  alias: osha
  func: configsObjectsShowAll
  help: Displays all available object IDs from configuration.



- name: ConfigsMorphsShow
  alias: msh
  func: configsMorphsShow
  help: Displays the min and max values of the specified morph.
  args:
  - name: id
    type: string
    required: true
    help: The morph ID to inspect.

- name: ConfigsMorphsShowAll
  alias: msha
  func: configsMorphsShowAll
  help: Displays all available morph IDs from configuration.
  


- name: ConfigsMorphPacksShowAll
  alias: mpsha
  func: configsMorphPacksShowAll
  help: Displays all available morph pack IDs from configuration.

- name: ConfigsMorphPacksShow
  alias: mpsh
  func: configsMorphPacksShow
  help: Displays the values of the specified morph pack.
  args:
  - name: id
    type: string
    required: true
    help: The morph pack ID to inspect.


- name: ConfigsStatsShowAll
  alias: ssha
  func: configsStatsShowAll
  help: Displays all available stat IDs from configuration.
  
- name: ConfigsStatsShow
  alias: ssh
  func: configsStatsShow
  help: Displays the values of the specified stat.
  args:
  - name: id
    type: string
    required: true
    help: The stat ID to inspect.
