version: 1
name: IncubatorConfigs
alias: ifconf
script: IF_Core_Debug_Global
help: Console functions to debug and inspect configuration data
subs:
- name: Reload
  alias: r
  func: configsReload 
  help: Reloads all configuration files.

- name: UpdateCaches
  alias: uc
  func: configsUpdateCaches
  help: Refreshes all internal caches from config data.



- name: ContainersShow
  alias: csh
  func: configsContainersShow
  help: Displays properties of the specified container from configuration.
  args:
  - name: id
    type: string
    required: true
    help: The container ID to inspect.

- name: ContainersShowAll
  alias: csha
  func: configsContainersShowAll
  help: Displays all available container IDs from configuration.



- name: LiquidsShow
  alias: lsh
  func: configsLiquidsShow
  help: Displays properties and morph effects of the specified liquid.
  args:
  - name: id
    type: string
    required: true
    help: The liquid ID to inspect.

- name: LiquidsShowAll
  alias: lsha
  func: configsLiquidsShowAll
  help: Displays all available liquid IDs from configuration.



- name: ObjectsShow
  alias: osh
  func: configsObjectsShow
  help: Displays properties and morph effects of the specified object.
  args:
  - name: id
    type: string
    required: true
    help: The object ID to inspect.

- name: ObjectsShowAll
  alias: osha
  func: configsObjectsShowAll
  help: Displays all available object IDs from configuration.



- name: MorphsShow
  alias: msh
  func: configsMorphsShow
  help: Displays the min and max values of the specified morph.
  args:
  - name: id
    type: string
    required: true
    help: The morph ID to inspect.

- name: MorphsShowAll
  alias: msha
  func: configsMorphsShowAll
  help: Displays all available morph IDs from configuration.
  


- name: MorphPacksShowAll
  alias: mpsha
  func: configsMorphPacksShowAll
  help: Displays all available morph pack IDs from configuration.

- name: MorphPacksShow
  alias: mpsh
  func: configsMorphPacksShow
  help: Displays the values of the specified morph pack.
  args:
  - name: id
    type: string
    required: true
    help: The morph pack ID to inspect.


- name: StatsShowAll
  alias: ssha
  func: configsStatsShowAll
  help: Displays all available stat IDs from configuration.
  
- name: StatsShow
  alias: ssh
  func: configsStatsShow
  help: Displays the values of the specified stat.
  args:
  - name: id
    type: string
    required: true
    help: The stat ID to inspect.
